# fly.toml app configuration file generated for reactivities-jul on 2023-09-14T13:33:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reactivities-jul"
primary_region = "lhr"

[build]
  image = "jnbofori/reactivities:latest"

# making sure app runs on port 8080
# and other non secret env variables here (from appsettings)
[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dv5ns7akx"
  Cloudinary__ApiKey="317397127519548"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
